Challenge/Controllers/ContactInfoController.cs
using Challenge.DataAccessLayer;
using Challenge.Models;
using Challenge.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Challenge.Controllers
{
    public class ContactInfoController : Controller
    {
        private readonly ContactContext db = new ContactContext();

        // GET: ContactInfo
        public ActionResult Index(/*string option, string search*/)
        {
           
            List<Contact> contacts1 = db.Contacts.ToList();
            List<Addresses> addresses1 = db.Addresses.ToList();

            var multitable = from c in contacts1
                             join ad in addresses1 on c.Address equals ad.Address into table1
                             from ad in table1.DefaultIfEmpty()
                             select new ContactInfo { Contacts = c, Addresses = ad };


           return View(multitable);
        }

    }
}

Challenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Challange</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Saberin Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact Info", "Index", "ContactInfo")</li>
                    <li>@Html.ActionLink("Contacts", "Index", "Contacts")</li>
                    <li>@Html.ActionLink("Addresses", "Index", "Addresses")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>